### ISSUE TITLE
Orocos Load Error

### ISSUE THREAD

**Issue by munirjojoverge** [uzh-rpg/eds-buildconf#3]
I followed the "Execution" steps and if fails when running the following:
javi@b46bcf1cc0d6:~/rock/dev/bundles/eds$ ruby scripts/slam/eds/run_eds_logs.rb --dataset=atrium --log_type=davis /tmp/atrium.log
Traceback (most recent call last):
	2: from scripts/slam/eds/run_eds_logs.rb:3:in `<main>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- orocos (LoadError)

**Comment by jhidalgocarrio** [comment]
Hi thanks for trying out the code. 
I think you are missing to source the environmental variables. This is the reason why ruby cannot find the _orocos_ library.
The env variables are in the file `env.sh` in `~/rock/dev/`

This is your error:
```
docker start eds ; docker attach eds # this is to enter in the docker container
docker:~ $ cd rock/dev   
docker:dev $ cd bundles/eds
docker:eds (master) $ ruby scripts/slam/eds/run_eds_logs.rb --dataset=atrium --log_type=davis /tmp/atrium.log
Traceback (most recent call last):
	2: from scripts/slam/eds/run_eds_logs.rb:3:in `<main>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- orocos (LoadError)
```
Please try the following (source the env.sh file before):
```
docker:eds (master) $ source ~/rock/dev/env.sh 
docker:eds (master) $ ruby scripts/slam/eds/run_eds_logs.rb --dataset=atrium --log_type=davis /tmp/atrium.log
pocolog.rb[INFO]: concatenated indexes in 0.00 seconds
pocolog.rb[INFO]: built full index in 0.02 seconds
Log time: 0:00:00.625 s:[0.005]  TASK STATE: OPTIMIZING 
```
Afterward, this should work. If you still have problems it is because the omniorb daemon is not running. Therefore run:
```
docker:eds (master) $  sudo /etc/init.d/omniorb4-nameserver stop
docker:eds (master) $  sudo rm -f /var/lib/omniorb/*
docker:eds (master) $  sudo /etc/init.d/omniorb4-nameserver start
```

**Comment by hmirh** [comment]
Thanks for your comment. I had the same problem and it solved by your solution.
But I got another error:

`[DEPRECATED] utilrb/hash/slice is deprecated, use backports' backports/2.5.0/hash/slice instead or the built-in method in Ruby >= 2.5
Typelib[WARN]: WARN: integrating typelib plugin using the TYPELIB_RUBY_PLUGIN_PATH environment
Typelib[WARN]: WARN: variable is deprecated. Just put a file called typelib_plugin.rb into a
Typelib[WARN]: WARN: subfolder from the RUBYLIB (e.g. base/typelib_plugin.rb)
Typelib[WARN]: WARN: Offending file: /home/labuser/rock/dev/install/share/typelib/ruby/base_types.rb
Gtk-Message: 12:38:25.294: Failed to load module "canberra-gtk-module"
WARN: no need to require 'object/singleton_class' anymore, it is built-in since Ruby 1.9
WARN: ColumnFormatter is deprecated, use the tty-table gem which provides
WARN: more functionality in a much nicer API
WARN Module#is_singleton? has been renamed to #singleton_class? to match the built-in method in Ruby 2.1+
WARN require 'utilrb/module/singleton_class_p instead of is_singleton?
Bundles[INFO]: Active bundles: eds, rock
`
`/home/labuser/rock/dev/tools/orogen/lib/orogen/loaders/base.rb:166:in `task_model_from_name': no task model eds::Task is registered (OroGen::TaskModelNotFound)
	15: from scripts/slam/eds/run_eds_logs.rb:47:in `<main>'
`
`cue in block in partition_run_options'
/home/labuser/rock/dev/tools/orogen/lib/orogen/loaders/aggregate.rb:204:in `deployment_model_from_name': there is no deployment named eds::Task on #<Orocos::DefaultLoader(1338): #<OroGen::Loaders::PkgConfig(438) gnulinux>,#<OroGen::Loaders::Files(44c) projects= typekits=>,#<Orocos::ROS::DefaultLoader packs=[] search_path=["/home/labuser/rock/dev/tools/orogen/lib/orogen/ros"]>> (OroGen::DeploymentModelNotFound)
`
`/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:548:in `rescue in rescue in block in partition_run_options': eds::Task is neither a task model nor a deployment name (OroGen::NotFound)
`


I would appreciate if you can help me in this regard.

**Comment by jhidalgocarrio** [comment]
Can you do the following in a terminal:
```
cd ~/rock/dev
source env.sh
autoproj build slam/orogen/eds
```
Can you show your output?

**Comment by hmirh** [comment]
I do appreciate your response.

The output is:

`
  operating system: ubuntu,debian - 20.04,20.04.4,lts,focal,fossa
  WARN: osdeps definition for cmake, previously defined in /home/labuser/.local/share/autoproj/gems/ruby/2.7.0/gems/autoproj-2.15.3/lib/autoproj/default.osdeps overridden by /home/labuser/rock/dev/autoproj/remotes/rock.core/rock.osdeps:
  WARN:   resp. apt-dpkg: cmake
  WARN:         osdep: build-essential
  WARN:   and   apt-dpkg: cmake
  WARN: gui/osgviz from /home/labuser/rock/dev/autoproj/remotes/rock.core/00new_packages.autobuild is overridden by the definition in /home/labuser/rock/dev/autoproj/remotes/osgviz/osgviz.autobuild
  WARN: tools/smurf from /home/labuser/rock/dev/autoproj/remotes/envire/libs.autobuild is overridden by the definition in /home/labuser/rock/dev/autoproj/remotes/rock.cpp/libs.autobuild
  WARN: slam/pcl from /home/labuser/rock/dev/autoproj/remotes/envire/libs.autobuild is overridden by the definition in /home/labuser/rock/dev/autoproj/remotes/rock/libs.autobuild
  typelib: using the castxml importer
  WARN: tools/msgpack-c from rock.core does not have a manifest
  building slam/orogen/eds (97%)
  environment already up-to-date
**Command failed
slam/orogen/eds(/home/labuser/rock/dev/slam/orogen/eds): failed in build phase**
    'make --jobserver-auth=5,6' returned status 2
    see /home/labuser/rock/dev/install/log/slam/orogen/eds-build.log for details
    last 10 lines are:

    [ 60%] Built target eds-tasks-gnulinux
    [ 74%] Built target eds-transport-typelib-gnulinux
    [ 88%] Built target eds-transport-mqueue-gnulinux
    [ 94%] Built target eds-proxies
    [ 97%] Linking CXX executable orogen_default_eds__Task
    /usr/bin/ld: /home/labuser/rock/dev/install/lib/libeds.so: undefined reference to `cv::fisheye::undistortPoints(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&)'
    collect2: error: ld returned 1 exit status
    make[2]: *** [CMakeFiles/orogen_default_eds__Task.dir/build.make:452: orogen_default_eds__Task] Error 1
    make[1]: *** [CMakeFiles/Makefile2:232: CMakeFiles/orogen_default_eds__Task.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2
`

**Comment by jhidalgocarrio** [comment]
It cannot find your opencv installation. Can you try?
```
cd ~/rock/dev
source env.sh
autoproj update slam/eds
autoproj build slam/eds
ldd install/lib/libeds.so
```

**Comment by hmirh** [comment]
By running the following command:

`autoproj update slam/eds`

The output is:

`operating system: ubuntu,debian - 20.04,20.04.4,lts,focal,fossa
  WARN: osdeps definition for cmake, previously defined in /home/labuser/.local/share/autoproj/gems/ruby/2.7.0/gems/autoproj-2.15.3/lib/autoproj/default.osdeps overridden by /home/labuser/rock/dev/autoproj/remotes/rock.core/rock.osdeps:
  WARN:   resp. apt-dpkg: cmake
  WARN:         osdep: build-essential
  WARN:   and   apt-dpkg: cmake
  WARN: gui/osgviz from /home/labuser/rock/dev/autoproj/remotes/rock.core/00new_packages.autobuild is overridden by the definition in /home/labuser/rock/dev/autoproj/remotes/osgviz/osgviz.autobuild
  WARN: tools/smurf from /home/labuser/rock/dev/autoproj/remotes/envire/libs.autobuild is overridden by the definition in /home/labuser/rock/dev/autoproj/remotes/rock.cpp/libs.autobuild
  WARN: slam/pcl from /home/labuser/rock/dev/autoproj/remotes/envire/libs.autobuild is overridden by the definition in /home/labuser/rock/dev/autoproj/remotes/rock/libs.autobuild
  already up-to-date slam/eds
  already up-to-date slam/ceres_solver
  already up-to-date perception/frame_helper
  already up-to-date base/types
  already up-to-date base/cmake
  already up-to-date base/logging
  already up-to-date perception/jpeg_conversion
  already up-to-date gui/vizkit3d
  already up-to-date typelib
  already up-to-date external/sisl
  typelib: using the castxml importer
  already up-to-date rtt_typelib
  already up-to-date gui/osg_qt4
  already up-to-date gui/osgviz
  already up-to-date utilrb
  already up-to-date rtt
  WARN: tools/msgpack-c from rock.core does not have a manifest
  building initial autoproj import log, this may take a while
  bundler: connected to https://rubygems.org/
  environment already up-to-date
Command finished successfully at 2022-05-26 13:08:16 -0600 (took 42 secs)`


The output of following command is:

`autoproj build slam/eds`

`operating system: ubuntu,debian - 20.04,20.04.4,lts,focal,fossa
  WARN: osdeps definition for cmake, previously defined in /home/labuser/.local/share/autoproj/gems/ruby/2.7.0/gems/autoproj-2.15.3/lib/autoproj/default.osdeps overridden by /home/labuser/rock/dev/autoproj/remotes/rock.core/rock.osdeps:
  WARN:   resp. apt-dpkg: cmake
  WARN:         osdep: build-essential
  WARN:   and   apt-dpkg: cmake
  WARN: gui/osgviz from /home/labuser/rock/dev/autoproj/remotes/rock.core/00new_packages.autobuild is overridden by the definition in /home/labuser/rock/dev/autoproj/remotes/osgviz/osgviz.autobuild
  WARN: tools/smurf from /home/labuser/rock/dev/autoproj/remotes/envire/libs.autobuild is overridden by the definition in /home/labuser/rock/dev/autoproj/remotes/rock.cpp/libs.autobuild
  WARN: slam/pcl from /home/labuser/rock/dev/autoproj/remotes/envire/libs.autobuild is overridden by the definition in /home/labuser/rock/dev/autoproj/remotes/rock/libs.autobuild
  typelib: using the castxml importer
  WARN: tools/msgpack-c from rock.core does not have a manifest
  environment already up-to-date
Command finished successfully at 2022-05-26 13:12:27 -0600 (took 9 secs)
`

The output of last command is:

`linux-vdso.so.1 (0x00007ffc2992b000)
	libboost_thread.so.1.71.0 => /lib/x86_64-linux-gnu/libboost_thread.so.1.71.0 (0x00007fdfe9f30000)
	libbase-types.so => /home/labuser/rock/dev/install/lib/libbase-types.so (0x00007fdfe9e86000)
	libyaml-cpp.so.0.6 => /lib/x86_64-linux-gnu/libyaml-cpp.so.0.6 (0x00007fdfe9e2b000)
	libframe_helper.so => /home/labuser/rock/dev/install/lib/libframe_helper.so (0x00007fdfe9df3000)
	libopencv_video.so.405 => /usr/local/lib/libopencv_video.so.405 (0x00007fdfe9d6b000)
	libopencv_calib3d.so.405 => /usr/local/lib/libopencv_calib3d.so.405 (0x00007fdfe9b1c000)
	libopencv_imgcodecs.so.405 => /usr/local/lib/libopencv_imgcodecs.so.405 (0x00007fdfe9ab8000)
	libopencv_features2d.so.405 => /usr/local/lib/libopencv_features2d.so.405 (0x00007fdfe99dc000)
	libopencv_imgproc.so.405 => /usr/local/lib/libopencv_imgproc.so.405 (0x00007fdfe7e5b000)
	libopencv_core.so.405 => /usr/local/lib/libopencv_core.so.405 (0x00007fdfe6e2a000)
	libceres.so.2 => /home/labuser/rock/dev/install/lib/libceres.so.2 (0x00007fdfe6b0d000)
	libglog.so.0 => /lib/x86_64-linux-gnu/libglog.so.0 (0x00007fdfe6ad8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdfe6ab5000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdfe68d3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdfe6784000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdfe6769000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdfe6577000)
	libsisl.so => /home/labuser/rock/dev/install/lib/libsisl.so (0x00007fdfe6435000)
	libboost_regex.so.1.71.0 => /lib/x86_64-linux-gnu/libboost_regex.so.1.71.0 (0x00007fdfe6335000)
	libjpeg_conversion.so => /home/labuser/rock/dev/install/lib/libjpeg_conversion.so (0x00007fdfe6329000)
	libopencv_dnn.so.405 => /usr/local/lib/libopencv_dnn.so.405 (0x00007fdfe5da6000)
	libopencv_flann.so.405 => /usr/local/lib/libopencv_flann.so.405 (0x00007fdfe5d1f000)
	libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fdfe5c98000)
	libwebp.so.6 => /lib/x86_64-linux-gnu/libwebp.so.6 (0x00007fdfe5c2e000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fdfe5bf6000)
	libtiff.so.5 => /lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fdfe5b75000)
	libopenjp2.so.7 => /lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007fdfe5b1f000)
	libIlmImf-2_3.so.24 => /lib/x86_64-linux-gnu/libIlmImf-2_3.so.24 (0x00007fdfe5840000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdfe5838000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fdfe581c000)
	libspqr.so.2 => /lib/x86_64-linux-gnu/libspqr.so.2 (0x00007fdfe57ee000)
	libcholmod.so.3 => /lib/x86_64-linux-gnu/libcholmod.so.3 (0x00007fdfe570b000)
	liblapack.so.3 => /lib/x86_64-linux-gnu/liblapack.so.3 (0x00007fdfe5043000)
	libf77blas.so.3 => /lib/x86_64-linux-gnu/libf77blas.so.3 (0x00007fdfe501f000)
	libcxsparse.so.3 => /lib/x86_64-linux-gnu/libcxsparse.so.3 (0x00007fdfe4ff0000)
	libgflags.so.2.2 => /lib/x86_64-linux-gnu/libgflags.so.2.2 (0x00007fdfe4fc5000)
	libunwind.so.8 => /lib/x86_64-linux-gnu/libunwind.so.8 (0x00007fdfe4fa8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdfea0d7000)
	libicui18n.so.66 => /lib/x86_64-linux-gnu/libicui18n.so.66 (0x00007fdfe4ca9000)
	libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007fdfe4ac3000)
	libbase-logging.so => /home/labuser/rock/dev/install/lib/libbase-logging.so (0x00007fdfe4ab6000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fdfe4a0d000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fdfe49e4000)
	libjbig.so.0 => /lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fdfe47d6000)
	libHalf.so.24 => /lib/x86_64-linux-gnu/libHalf.so.24 (0x00007fdfe4791000)
	libIex-2_3.so.24 => /lib/x86_64-linux-gnu/libIex-2_3.so.24 (0x00007fdfe476e000)
	libIlmThread-2_3.so.24 => /lib/x86_64-linux-gnu/libIlmThread-2_3.so.24 (0x00007fdfe4764000)
	libsuitesparseconfig.so.5 => /lib/x86_64-linux-gnu/libsuitesparseconfig.so.5 (0x00007fdfe475f000)
	libblas.so.3 => /lib/x86_64-linux-gnu/libblas.so.3 (0x00007fdfe4399000)
	libamd.so.2 => /lib/x86_64-linux-gnu/libamd.so.2 (0x00007fdfe438e000)
	libcolamd.so.2 => /lib/x86_64-linux-gnu/libcolamd.so.2 (0x00007fdfe4383000)
	libccolamd.so.2 => /lib/x86_64-linux-gnu/libccolamd.so.2 (0x00007fdfe4376000)
	libcamd.so.2 => /lib/x86_64-linux-gnu/libcamd.so.2 (0x00007fdfe436a000)
	libmetis.so.5 => /lib/x86_64-linux-gnu/libmetis.so.5 (0x00007fdfe40fc000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fdfe40ba000)
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007fdfe3df2000)
	libatlas.so.3 => /lib/x86_64-linux-gnu/libatlas.so.3 (0x00007fdfe3a66000)
	libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007fdfe1fa3000)
	libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fdfe1f59000)`

It seems all these run correctly. But when I run again:

`~/rock/dev$ source ~/rock/dev/env.sh 
~/rock/dev$ cd bundles/eds
~/rock/dev/bundles/eds$ source ~/rock/dev/env.sh 
~/rock/dev/bundles/eds$ ruby scripts/slam/eds/run_eds_logs.rb --dataset=atrium --log_type=davis /tmp/atrium.log`

I got the same error. :(

**Comment by hmirh** [comment]
This is the exact output:

`[DEPRECATED] utilrb/hash/slice is deprecated, use backports' backports/2.5.0/hash/slice instead or the built-in method in Ruby >= 2.5
Typelib[WARN]: WARN: integrating typelib plugin using the TYPELIB_RUBY_PLUGIN_PATH environment
Typelib[WARN]: WARN: variable is deprecated. Just put a file called typelib_plugin.rb into a
Typelib[WARN]: WARN: subfolder from the RUBYLIB (e.g. base/typelib_plugin.rb)
Typelib[WARN]: WARN: Offending file: /home/labuser/rock/dev/install/share/typelib/ruby/base_types.rb
Gtk-Message: 13:13:30.808: Failed to load module "canberra-gtk-module"
WARN: no need to require 'object/singleton_class' anymore, it is built-in since Ruby 1.9
WARN: ColumnFormatter is deprecated, use the tty-table gem which provides
WARN: more functionality in a much nicer API
WARN Module#is_singleton? has been renamed to #singleton_class? to match the built-in method in Ruby 2.1+
WARN require 'utilrb/module/singleton_class_p instead of is_singleton?
Bundles[INFO]: Active bundles: eds, rock
orocos.rb[WARN]: ignoring configuration file /home/labuser/rock/dev/bundles/eds/config/orogen/apriltags::Task.yml as there are no corresponding task model
orocos.rb[WARN]: ignoring configuration file /home/labuser/rock/dev/bundles/eds/config/orogen/eds::Task.yml as there are no corresponding task model
orocos.rb[WARN]: ignoring configuration file /home/labuser/rock/dev/bundles/eds/config/orogen/midas::Task.yml as there are no corresponding task model
Bundles[INFO]: log files are going in /tmp/20220526-1313
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/ruby_tasks/task_context.rb:45: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/ruby_tasks/task_context.rb:61: warning: The called method `initialize' is defined here
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/name_service.rb:317: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/name_service.rb:606: warning: The called method `get' is defined here
/home/labuser/rock/dev/install/lib/ruby/2.7.0/transformer/runtime.rb:262: warning: Splitting the last argument into positional and keyword parameters is deprecated
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:798: warning: The called method `run' is defined here
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:816: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:977: warning: The called method `spawn' is defined here
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/name_service.rb:617: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/task_context.rb:135: warning: The called method `initialize' is defined here
/home/labuser/rock/dev/base/scripts/lib/rock/bundles.rb:411: warning: Splitting the last argument into positional and keyword parameters is deprecated
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:135: warning: The called method `run' is defined here
orocos.rb[WARN]: killing running task contexts and deployments because of unhandled exception
orocos.rb[WARN]:   /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:548:in `rescue in rescue in block in partition_run_options': eds::Task is neither a task model nor a deployment name
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:545:in `rescue in block in partition_run_options'
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:542:in `block in partition_run_options'
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:537:in `each'
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:537:in `partition_run_options'
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:645:in `parse_run_options'
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:808:in `run'
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
orocos.rb[WARN]:     /home/labuser/rock/dev/base/scripts/lib/rock/bundles.rb:411:in `block in run'
orocos.rb[WARN]:     /home/labuser/rock/dev/install/lib/ruby/2.7.0/transformer/runtime.rb:264:in `block in start_broadcaster'
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:1343:in `guard'
orocos.rb[WARN]:     /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
orocos.rb[WARN]:     /home/labuser/rock/dev/install/lib/ruby/2.7.0/transformer/runtime.rb:262:in `start_broadcaster'
orocos.rb[WARN]:     /home/labuser/rock/dev/base/scripts/lib/rock/bundles.rb:410:in `run'
orocos.rb[WARN]:     scripts/slam/eds/run_eds_logs.rb:47:in `<main>'
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/ports_base.rb:66: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/typekits.rb:284: warning: The called method `find_type_by_orocos_type_name' is defined here
orocos.rb[WARN]: sending SIGINT to transformer_broadcaster
Traceback (most recent call last):
	20: from scripts/slam/eds/run_eds_logs.rb:47:in `<main>'
	19: from /home/labuser/rock/dev/base/scripts/lib/rock/bundles.rb:410:in `run'
	18: from /home/labuser/rock/dev/install/lib/ruby/2.7.0/transformer/runtime.rb:262:in `start_broadcaster'
	17: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
	16: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:1343:in `guard'
	15: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
	14: from /home/labuser/rock/dev/install/lib/ruby/2.7.0/transformer/runtime.rb:264:in `block in start_broadcaster'
	13: from /home/labuser/rock/dev/base/scripts/lib/rock/bundles.rb:411:in `block in run'
	12: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
	11: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:808:in `run'
	10: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:645:in `parse_run_options'
	 9: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:537:in `partition_run_options'
	 8: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:537:in `each'
	 7: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:543:in `block in partition_run_options'
	 6: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/default_loader.rb:58:in `task_model_from_name'
	 5: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/default_loader.rb:58:in `synchronize'
	 4: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/default_loader.rb:59:in `block in task_model_from_name'
	 3: from /home/labuser/rock/dev/tools/orogen/lib/orogen/loaders/aggregate.rb:78:in `task_model_from_name'
	 2: from /home/labuser/rock/dev/tools/orogen/lib/orogen/loaders/aggregate.rb:78:in `each'
	 1: from /home/labuser/rock/dev/tools/orogen/lib/orogen/loaders/aggregate.rb:83:in `block in task_model_from_name'
/home/labuser/rock/dev/tools/orogen/lib/orogen/loaders/base.rb:166:in `task_model_from_name': no task model eds::Task is registered (OroGen::TaskModelNotFound)
	15: from scripts/slam/eds/run_eds_logs.rb:47:in `<main>'
	14: from /home/labuser/rock/dev/base/scripts/lib/rock/bundles.rb:410:in `run'
	13: from /home/labuser/rock/dev/install/lib/ruby/2.7.0/transformer/runtime.rb:262:in `start_broadcaster'
	12: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
	11: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:1343:in `guard'
	10: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
	 9: from /home/labuser/rock/dev/install/lib/ruby/2.7.0/transformer/runtime.rb:264:in `block in start_broadcaster'
	 8: from /home/labuser/rock/dev/base/scripts/lib/rock/bundles.rb:411:in `block in run'
	 7: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
	 6: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:808:in `run'
	 5: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:645:in `parse_run_options'
	 4: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:537:in `partition_run_options'
	 3: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:537:in `each'
	 2: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:542:in `block in partition_run_options'
	 1: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:546:in `rescue in block in partition_run_options'
/home/labuser/rock/dev/tools/orogen/lib/orogen/loaders/aggregate.rb:204:in `deployment_model_from_name': there is no deployment named eds::Task on #<Orocos::DefaultLoader(1338): #<OroGen::Loaders::PkgConfig(438) gnulinux>,#<OroGen::Loaders::Files(44c) projects= typekits=>,#<Orocos::ROS::DefaultLoader packs=[] search_path=["/home/labuser/rock/dev/tools/orogen/lib/orogen/ros"]>> (OroGen::DeploymentModelNotFound)
	15: from scripts/slam/eds/run_eds_logs.rb:47:in `<main>'
	14: from /home/labuser/rock/dev/base/scripts/lib/rock/bundles.rb:410:in `run'
	13: from /home/labuser/rock/dev/install/lib/ruby/2.7.0/transformer/runtime.rb:262:in `start_broadcaster'
	12: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
	11: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:1343:in `guard'
	10: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
	 9: from /home/labuser/rock/dev/install/lib/ruby/2.7.0/transformer/runtime.rb:264:in `block in start_broadcaster'
	 8: from /home/labuser/rock/dev/base/scripts/lib/rock/bundles.rb:411:in `block in run'
	 7: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
	 6: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:808:in `run'
	 5: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:645:in `parse_run_options'
	 4: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:537:in `partition_run_options'
	 3: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:537:in `each'
	 2: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:542:in `block in partition_run_options'
	 1: from /home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:545:in `rescue in block in partition_run_options'
/home/labuser/rock/dev/tools/orocos.rb/lib/orocos/process.rb:548:in `rescue in rescue in block in partition_run_options': eds::Task is neither a task model nor a deployment name (OroGen::NotFound)
`

**Comment by hmirh** [comment]
@jhidalgocarrio Could you help me to solve this error? I till have an error in loading OroGen.
