### ISSUE TITLE
Vizkit[ERROR]：Cannot load Vizkit3D plugin

### ISSUE THREAD

**Issue by chenhy396** [uzh-rpg/eds-buildconf#9]
Hello, thank you for this great work! But I was stuck with the following problem.
When I run `ruby scripts/gui/eds_visualization.rb `, error occurs:

```
(base) huoyu@huoyuWP:~/local/installpackage/rock_3/dev/bundles/eds$ ruby scripts/gui/eds_visualization.rb 
Typelib[WARN]: WARN: integrating typelib plugin using the TYPELIB_RUBY_PLUGIN_PATH environment
Typelib[WARN]: WARN: variable is deprecated. Just put a file called typelib_plugin.rb into a
Typelib[WARN]: WARN: subfolder from the RUBYLIB (e.g. base/typelib_plugin.rb)
Typelib[WARN]: WARN: Offending file: /home/huoyu/local/installpackage/rock_3/dev/install/share/typelib/ruby/base_types.rb
/home/huoyu/local/installpackage/rock_3/dev/tools/utilrb/lib/utilrb/pkgconfig.rb:628: warning: Insecure world writable dir /home/huoyu/local/installpackage/rock_3/dev/tools/log_tools/bin in PATH, mode 040777
Bundles[INFO]: Active bundles: eds, rock
orocos.rb[WARN]: ignoring configuration file /home/huoyu/local/installpackage/rock_3/dev/bundles/eds/config/orogen/apriltags::Task.yml as there are no corresponding task model
orocos.rb[WARN]: ignoring configuration file /home/huoyu/local/installpackage/rock_3/dev/bundles/eds/config/orogen/midas::Task.yml as there are no corresponding task model
Bundles[INFO]: log files are going in /tmp/20221013-1643
Vizkit[ERROR]: Cannot load Vizkit3D pluign /home/huoyu/local/installpackage/rock_3/dev/install/lib/libbase-viz.so. Library seems to be incompatible to the qt loader. Have you created a plugin factory?
Traceback (most recent call last):
	6: from scripts/gui/eds_visualization.rb:81:in `<main>'
	5: from /home/huoyu/local/installpackage/rock_3/dev/gui/vizkit/lib/vizkit/plugin_accessor.rb:40:in `block in add_plugin_spec'
	4: from /home/huoyu/local/installpackage/rock_3/dev/gui/vizkit/lib/vizkit/uiloader.rb:341:in `create_plugin'
	3: from /home/huoyu/local/installpackage/rock_3/dev/gui/vizkit/lib/vizkit/plugin.rb:549:in `create_plugin'
	2: from /home/huoyu/local/installpackage/rock_3/dev/gui/vizkit/lib/vizkit/uiloader.rb:46:in `block in register_3d_plugin'
	1: from /home/huoyu/local/installpackage/rock_3/dev/gui/vizkit/lib/vizkit/cplusplus_extensions/vizkit_widget.rb:241:in `createPlugin'
/home/huoyu/local/installpackage/rock_3/dev/gui/vizkit/lib/vizkit/cplusplus_extensions/vizkit_widget.rb:156:in `load_plugin': Cannot load /home/huoyu/local/installpackage/rock_3/dev/install/lib/libbase-viz.so. Last error is: The plugin '/home/huoyu/local/installpackage/rock_3/dev/install/lib/libbase-viz.so' uses incompatible Qt library. Expected build key "x86_64 linux g++-7 full-config", got "x86_64 linux g++-4 full-config" (RuntimeError)
```

I'm not sure if the error of incompatibility is relevant with the warnings above. It seems that the error is due to the build key. I've searched for `qconfig.h `where the `QT_BUILD_KEY` is defined. And I find it appears in different files.

In `/usr/include/qt4/QtCore/qconfig.h`:
```
#define QT_BUILD_KEY "x86_64 linux g++-4 full-config"
#define QT_BUILD_KEY_COMPAT "x86_64 Linux g++-4 full-config"
```

In `/usr/local/Trolltech/Qt-4.8.6/include/QtCore/qconfig.h`:
```
#define QT_BUILD_KEY "x86_64 linux g++-7 full-config"
#define QT_BUILD_KEY_COMPAT "x86_64 Linux g++-7 full-config"
```

I'm not sure how the first one `qconfig.h`(`/usr/include/qt4/QtCore/qconfig.h`) was constructed, but I recognize the second one was built manually outside the `autoproj`. I guess it chooses the first one, so I've tried to modify the `#define QT_BUILD_KEY"x86_64 linux g++-4 full-config"` to `#define QT_BUILD_KEY"x86_64 linux g++-7 full-config" `, and so to the `QT_BUILD_KEY_COMPAT`, but error is still the same. Is there anything I've missed?

I'm not so familiar with setting up environment. And it sticks with me for quite a long time. It would be grateful if anyone could help me out.

**Comment by chenhy396** [comment]
Problem solved by upgrading the version of Ubuntu to 20.04 LTS.
